openapi: 3.0.0
info:
  title: "Trail Application REST API"
  description: "An API to manage trails, locations, and trail information"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /trails:
    get:
      operationId: "trails.get_all_trails"
      summary: "Get all trails"
      tags:
        - "Trails"
      responses:
        '200':
          description: "OK"
    post:
      operationId: "trails.create_trail"
      summary: "Create a new trail"
      tags:
        - "Trails"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Trail"
      responses:
        '201':
          description: "Created"

  /trails/{trail_id}:
    get:
      operationId: "trails.get_trail_by_id"
      summary: "Get details of a specific trail"
      tags:
        - "Trails"
      parameters:
        - name: "trail_id"
          in: path
          required: true
          schema:
            type: "integer"
      responses:
        '200':
          description: "OK"
        '404':
          description: "Trail not found"
    put:
      operationId: "trails.update_trail"
      summary: "Update a trail"
      tags:
        - "Trails"
      parameters:
        - name: "trail_id"
          in: path
          required: true
          schema:
            type: "integer"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Trail"
      responses:
        '200':
          description: "OK"
        '404':
          description: "Trail not found"
    delete:
      operationId: "trails.delete_trail"
      summary: "Delete a trail"
      tags:
        - "Trails"
      parameters:
        - name: "trail_id"
          in: path
          required: true
          schema:
            type: "integer"
      responses:
        '204':
          description: "No content"
        '404':
          description: "Trail not found"

components:
  schemas:
    Trail:
      type: object
      required:
        - TrailName
      properties:
        TrailID:
          type: integer
        TrailName:
          type: string
        CreatedAt:
          type: string
          format: date-time

